
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Redis:
        class: Redis
        calls:
            - connect:
                  - '%env(string:REDIS_HOST)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    Symfony\Component\Cache\Adapter\RedisAdapter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@Redis'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Application\Shared\Command\CommandHandlerInterface:
            tags: [ 'cqrs.command.handler' ]
        App\Application\Shared\Query\QueryHandlerInterface:
            tags: [ 'cqrs.query.handler' ]

    App\Infrastructure\Shared\CommandBus\CommandBus:
        arguments:
            - !tagged 'cqrs.command.handler'

    App\Infrastructure\Shared\QueryBus\QueryBus:
        arguments:
            - !tagged 'cqrs.query.handler'